import streamlit as st
import pandas as pd

from src.data_management import load_pkl_file, load_electricity_data
from src.machine_learning.predict_electricity_cost import prepare_features, predict_cost


def page_predict_electricity_cost_body():

    st.write("### 🔌 Electricity Cost Prediction")

    st.info(
        "Enter site characteristics below to estimate the expected **monthly electricity cost (USD)**."
        "The prediction is generated by the trained Random Forest model."
    )

    st.write("---")

    version = "v1"
    model_path=f"outputs/ml_pipeline/electricity_cost/{version}"

    model = load_pkl_file(f"{model_path}/random_forest_model.pkl")
    model_features = load_pkl_file(f"{model_path}/model_features.pkl")

    # load dataset
    df = load_electricity_data()
    
    st.write("### Site profile inputs")

    col1, col2 = st.columns(2)

    with col1:
        site_area = st.number_input(
            "Site area (m²)",
            min_value=int(df["site_area"].min()) if "site_area" in df.columns else 1,
            max_value=int(df["site_area"].max()) if "site_area" in df.columns else 20000,
            value=int(df["site_area"].median()) if "site_area" in df.columns else 2750,
            step=1,
        )

        resident_count = st.number_input(
            "Resident / occupant count",
            min_value=int(df["resident_count"].min()) if "resident_count" in df.columns else 0,
            max_value=int(df["resident_count"].max()) if "resident_count" in df.columns else 10000,
            value=int(df["resident_count"].median()) if "resident_count" in df.columns else 40,
            step=1,
        )

        structure_type = st.selectbox(
            "Structure type",
            options=["Commercial", "Residential", "Mixed-use", "Industrial"],
            index=0,
        )

        issue_resolution_time = st.number_input(
            "Issue resolution time (hours)",
            min_value=int(df["issue_resolution_time"].min()) if "issue_resolution_time" in df.columns else 1,
            max_value = int(df["issue_resolution_time"].max()) if "issue_resolution_time" in df.columns else 72,
            value=int(df["issue_resolution_time"].median()) if "issue_resolution_time" in df.columns else 24,
            step=1,
        )

    with col2:
        water_consumption = st.number_input(
            "Water consumption (litres/day)",
            min_value=int(df["water_consumption"].min()) if "water_consumption" in df.columns else 0,
            max_value=int(df["water_consumption"].max()) if "water_consumption" in df.columns else 20000,
            value=int(df["water_consumption"].median()) if "water_consumption" in df.columns else 3000,
            step=50,
        )

        recycling_rate = st.slider(
            "Recycling rate (%)",
            min_value=0,
            max_value=100,
            value=int(df["recycling_rate"].median()) if "recycling_rate" in df.columns else 50,
        )

        utilisation_rate = st.slider(
            "Utilisation rate (%)",
            min_value=0,
            max_value=100,
            value=int(df["utilisation_rate"].median()) if "utilisation_rate" in df.columns else 70,
        )

        air_quality_index = st.number_input(
            "Air quality index (AQI)",
            min_value=int(df["air_quality_index"].min()) if "air_quality_index" in df.columns else 0,
            max_value=int(df["air_quality_index"].max()) if "air_quality_index" in df.columns else 500,
            value=int(df["air_quality_index"].median()) if "air_quality_index" in df.columns else 100,
            step=5,
        )

    st.write("---")

    user_inputs = {
        "site_area": float(site_area),
        "water_consumption": float(water_consumption),
        "recycling_rate": float(recycling_rate),
        "utilisation_rate": float(utilisation_rate),
        "air_quality_index": float(air_quality_index),
        "issue_resolution_time": float(issue_resolution_time),
        "resident_count": int(resident_count),
        "structure_type": structure_type,
    }

    if st.button("Predict Electricity Cost"):
        X_live = prepare_features(user_inputs=user_inputs, model_features=model_features)

        pred = predict_cost(model=model, X_live=X_live)

        st.success(f"💡 **Estimated Monthly Electricity Cost:** US$ {pred:,.2f}")

        st.caption(
            "This prediction is an estimate based on patterns in the historical dataset.\n"
            "Actual costs may vary due to factors not included in the data."
        )
